#!/bin/bash

apt-get update
apt-get install -y python-software-properties
echo | add-apt-repository ppa:saltstack/salt
apt-get update
apt-get install -y salt-minion

ln -sf /srv/salt/etc/salt/minion /etc/salt/minion

service salt-minion restart

# salt-call state.highstate
